version: '3.7'

services:
  jenkins:
    build: .
    container_name: jenkins
    ports:
      - "8080:8080"
    networks:
      - ci-network
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
  
  sonarqube:
    image: sonarqube
    ports:
      - 9000:9000
    networks:
      - ci-network

volumes:
  jenkins_home:

networks:
  ci-network:
    external: true