version: '3.7'

services:
  jenkins:
    build: .
    platform: linux/amd64
    container_name: jenkins
    ports:
      - "8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
  
  sonarqube:
    image: sonarqube
    ports:
      - 9000:9000
    volumes:
      - sonarqube_data:/opt/sonarqube/data

volumes:
  jenkins_home:
  sonarqube_data:
